### ISSUE TITLE
Simplify code using constant

### ISSUE THREAD

**Issue by OleksiiNikitenko** [Anarasty/tpr-lab4#1]
Hi @Anarasty,
Please, unify check countries input. Instead of hardcoding by storing it in a variable, You should create a new constant min_countries_amount with specific value and specify it in config file like a max_countries_amount constant. Thank you.
https://github.com/Anarasty/tpr-lab4/blob/15d1d945cabebc0ad708215b36faef7f3918cced/src/input.py#L46

**Comment by Anarasty** [comment]
Fixed bug according your examination. Please, check it.

**Comment by OleksiiNikitenko** [comment]
@Anarasty, everything is great, according your last commit. Nice job)
